### ISSUE TITLE
DFU fails with permissions error or device not found error

### ISSUE THREAD

**Issue by vraoresearch** [01org/CODK-M#23]
# Test Setup

**_VMWare Workstation 12 Pro - Version 12.1.1 build-3770994_**

> Host System: Intel DZ77GA-70K with 32GB RAM and Intel Core i7-3770 @ 3.4GHz 
> Host OS: Microsoft Windows 10 Pro Version: 1607 Build: 14393.105
> Guest System: Ubuntu 14.04.5 with 16GB RAM and 2CPU - 2 Cores
> Arduino IDE installed on Host: v1.6.11 with Curie 1.0.6
> CODK-M version: Checked out from GitHub on Sep 11 16:27
> Other Info: 
> *Removed modemmanager using sudo apt-get purge modemmanager
> *Arduino 101 device connected: USB 3.0 (Blue) xHCI port
> *USB 3.0 enabled on VM Settings
## Problem 1

Running 

```
make upload SERIAL_PORT=/dev/ttyACM0
```

results in a Permission Error

```
serial.serialutil.SerialException: could not open port /dev/ttyACM0: [Errno 13] Permission denied: '/dev/ttyACM0'
make: *** [upload] Error 1
```
### Debug Info

**Enumerated USB**

```
$>lsusb
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 001 Device 005: ID 0e0f:0002 VMware, Inc. Virtual USB Hub
Bus 001 Device 013: ID 8087:0ab6 Intel Corp. 
Bus 001 Device 004: ID 0e0f:0002 VMware, Inc. Virtual USB Hub
Bus 001 Device 003: ID 0e0f:0008 VMware, Inc. 
Bus 001 Device 002: ID 0e0f:0003 VMware, Inc. Virtual Mouse
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 003 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 004 Device 002: ID 0e0f:0002 VMware, Inc. Virtual USB Hub
Bus 004 Device 001: ID 1d6b:0001 Linux Foundation 1.1 root hub
```

Curie is present as Device 013 on Bus 001

**Check if device is present**

```
$> ls /dev/ttyACM0
/dev/ttyACM0
```

Device name exists

**Check Permissions**

```
$>ls -l  /dev/ttyACM0
crw-rw---- 1 root dialout 166, 0 Sep  9 10:19 /dev/ttyACM0
```

So user **root** and members of group **dialout** can access the device.

**Check if member of dialout group**

```
$>groups ${USER}
vraoresearch : vraoresearch adm cdrom sudo dip plugdev lpadmin sambashare
```

Not a member so need to add self.

**Add self to dialout group**

```
$>sudo gpasswd --add ${USER} dialout
```
## Problem 2

After adding user to dialout group and checking, running 

```
make upload SERIAL_PORT=/dev/ttyACM0
```

results in a new error. 

```
...
/home/vraoresearch/CODK/CODK-M/arc/arc32/bin/arc-elf32-objcopy -S -O ihex -R .note -R .comment -R COMMON -R .eh_frame  arc.elf arc.hex
Resetting port /dev/ttyACM0
/home/vraoresearch/CODK/CODK-M/arc/bin/resetPort.py /dev/ttyACM0
Resetting /dev/ttyACM0
Traceback (most recent call last):
  File "/home/vraoresearch/CODK/CODK-M/arc/bin/resetPort.py", line 12, in <module>
    mySerial = serial.Serial(serialPath, 1200)
  File "/usr/lib/python2.7/dist-packages/serial/serialutil.py", line 261, in __init__
    self.open()
  File "/usr/lib/python2.7/dist-packages/serial/serialposix.py", line 278, in open
    raise SerialException("could not open port %s: %s" % (self._port, msg))
serial.serialutil.SerialException: could not open port /dev/ttyACM0: [Errno 2] No such file or directory: '/dev/ttyACM0'
make[1]: *** [upload] Error 1
make[1]: Leaving directory `/home/vraoresearch/CODK/CODK-M/arc/examples/ASCIITable'
make: *** [upload-arc-dfu] Error 2
```
### Debug Info

Running

```
$>dmesg
```

Produces the following output

```
...
[ 2405.698829] usb 1-3.1: USB disconnect, device number 11
[ 2721.314360] usb 1-3.1: new full-speed USB device number 12 using xhci_hcd
[ 2721.519369] usb 1-3.1: New USB device found, idVendor=8087, idProduct=0aba
[ 2721.519372] usb 1-3.1: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[ 2721.519374] usb 1-3.1: Product: ATP-Dev1.0
[ 2721.519375] usb 1-3.1: Manufacturer: Intel
[ 2721.519376] usb 1-3.1: SerialNumber: 00.01
[ 2725.545184] usb 1-3.1: USB disconnect, device number 12
[ 2727.513155] usb 1-3.1: new full-speed USB device number 13 using xhci_hcd
[ 2727.706841] usb 1-3.1: New USB device found, idVendor=8087, idProduct=0ab6
[ 2727.706844] usb 1-3.1: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[ 2727.706845] usb 1-3.1: Product: CDC-ACM
[ 2727.706846] usb 1-3.1: Manufacturer: Intel
[ 2727.706847] usb 1-3.1: SerialNumber: 00.01
[ 2727.707157] usb 1-3.1: ep 0x81 - rounding interval to 64 microframes, ep desc says 80 microframes
[ 2727.720365] cdc_acm 1-3.1:1.0: ttyACM0: USB ACM device
[ 3423.204338] usb 1-3.1: USB disconnect, device number 13

```

**Comment by eriknyquist** [comment]
Hi @vraoresearch, when was the last time you grabbed the latest? Frequent updates are being made daily.

**Comment by eriknyquist** [comment]
Oh sorry I see you said Sept 11. OK so can you update everything and try again? there have been quite a few updates since the 11th.

**Comment by bbaltz505** [comment]
The permission issue is handled by the "sudo make install-dep" step now (as of Monday evening), although users may ave to logout/in for the new group to take effect. It sounds like you did this manually. The removal of modemmanger has also been added to the "install-dep" target (as of yesterday). I know you made both of these fixes manually but can you pull the latest CODK-M code and re-run the "sudo make install-dep" command? I'll need to check if there is another cause for that start-up delay that's keeping the board in DFU mode.

**Comment by bbaltz505** [comment]
hello.
Can you replace the /etc/udev/rules.d/99-dfu.rules contents with with:

```
ATTRS{idVendor}=="8087", ATTRS{idProduct}=="0ab[a6]", ENV{ID_MM_DEVICE_IGNORE}="1"
ATTRS{idVendor}=="8087", ATTRS{idProduct}=="0ab[a6]", ENV{MTP_NO_PROBE}="1"
SUBSYSTEM=="tty", ENV{ID_REVISION}=="8087", ENV{ID_MODEL_ID}=="0ab6", MODE="0666"
SUBSYSTEM=="usb", ATTR{idVendor}=="8087", ATTR{idProduct}=="0aba", MODE="666"
```

and then run:
`sudo service udev restart`
and see if that helps with the delay. I was able to reproduce your problem (even after removing modemmanager) and this change seemed to fix it.

**Comment by vraoresearch** [comment]
Sure...
I will setup a fresh VM to ensure that only the install-dep rule makes the changes.

**Comment by bbaltz505** [comment]
Thanks.
The proposed changes to 99-dfu.rules I proposed above are not in GitHub yet. If you have trouble with the port after setting up a clean VM and CODK install, try manually making the udev file changes and see if that resolves the issue.

**Comment by vraoresearch** [comment]
OK. This will take about an hour... I will try the udev rule change first. 
VMWare has also pushed an update to Workstation so that may also change things...

**Comment by vraoresearch** [comment]
Looks like the latest changes seem to be getting applied.  Also looks like modemmanager is getting installed later by some other process as it isn't there on a clean system.

```
dpkg --purge modemmaneger
dpkg: warning: ignoring request to remove modemmaneger which isn't installed
usermod -a -G dialout vraoresearch
vraoresearch@ubuntu:~/CODK/CODK-M$
```

**Comment by vraoresearch** [comment]
## New Problem!

**What Changed:**
- VMWare Workstation 12 Pro is now  Version 12.5.0 build-4352439
- CODK-M Checked out Sep 14 16:28

Following the new instructions for installing CODK-M (i.e. building each core and uploading each core)

```
make upload-x86-dfu
```

This seems to work successfully

```
Opening DFU capable USB device...
ID 8087:0aba
Run-time device DFU version 0011
Claiming USB DFU Interface...
Setting Alternate Setting #2 ...
Determining device status: state = dfuIDLE, status = 0
dfuIDLE, continuing
DFU mode device DFU version 0011
Device returned transfer size 2048
Copying data from PC to DFU device
Download    [=========================] 100%        46432 bytes
Download done.
state(2) = dfuIDLE, status(0) = No error condition is present
Done!
Resetting USB to switch back to runtime mode

!!!SUCCESS!!!
```

However, now the board is now recognized as two active devices...
I see two board icons on my VM , although lsusb is reporting only one device and only /dev/ttyACM0 is present.

dmesg output is shown below:

```
[ 2558.386102] usb 1-2: USB disconnect, device number 5
[ 2559.209985] usb 1-2: new full-speed USB device number 6 using xhci_hcd
[ 2559.454850] usb 1-2: New USB device found, idVendor=8087, idProduct=0aba
[ 2559.454853] usb 1-2: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[ 2559.454854] usb 1-2: Product: ATP-Dev1.0
[ 2559.454855] usb 1-2: Manufacturer: Intel
[ 2559.454856] usb 1-2: SerialNumber: 00.01
[ 2561.694108] usb 1-2: USB disconnect, device number 6
[ 2563.625471] usb 1-2: new full-speed USB device number 7 using xhci_hcd
[ 2563.865247] usb 1-2: New USB device found, idVendor=8087, idProduct=0aba
[ 2563.865250] usb 1-2: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[ 2563.865252] usb 1-2: Product: ATP-Dev1.0
[ 2563.865253] usb 1-2: Manufacturer: Intel
[ 2563.865254] usb 1-2: SerialNumber: 00.01
[ 2566.320483] usb 1-2: USB disconnect, device number 7
[ 2573.242810] usb 1-2: new full-speed USB device number 8 using xhci_hcd
[ 2573.480836] usb 1-2: New USB device found, idVendor=8087, idProduct=0ab6
[ 2573.480839] usb 1-2: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[ 2573.480841] usb 1-2: Product: CDC-ACM
[ 2573.480841] usb 1-2: Manufacturer: Intel
[ 2573.480842] usb 1-2: SerialNumber: 00.01
[ 2573.481111] usb 1-2: ep 0x81 - rounding interval to 64 microframes, ep desc says 80 microframes
[ 2573.482892] cdc_acm 1-2:1.0: ttyACM0: USB ACM device
```

If I continue ...

```
make upload-arc-dfu
```

The Arc update results in an error.

```
/home/vraoresearch/CODK/CODK-M/arc/bin/resetPort.py /dev/ttyACM0
Resetting /dev/ttyACM0
Traceback (most recent call last):
  File "/home/vraoresearch/CODK/CODK-M/arc/bin/resetPort.py", line 12, in <module>
    mySerial = serial.Serial(serialPath, 1200)
  File "/usr/lib/python2.7/dist-packages/serial/serialutil.py", line 261, in __init__
    self.open()
  File "/usr/lib/python2.7/dist-packages/serial/serialposix.py", line 278, in open
    raise SerialException("could not open port %s: %s" % (self._port, msg))
serial.serialutil.SerialException: could not open port /dev/ttyACM0: [Errno 13] Permission denied: '/dev/ttyACM0'
make[1]: *** [upload] Error 1
make[1]: Leaving directory `/home/vraoresearch/CODK/CODK-M/arc/examples/ASCIITable'
make: *** [upload-arc-dfu] Error 2
```

### Debug Info

```
groups ${USER}
vraoresearch : vraoresearch adm dialout cdrom sudo dip plugdev lpadmin sambashare
```

and

```
ls -l /dev/ttyA*
crw-rw---- 1 root dialout 166, 0 Sep 14 16:30 /dev/ttyACM0
```

Unplugging the board releases both icons. I checked device manager for ghost COM ports and there were none. Also updating the udev rules did not change the permission problem. However the board seems to switch to CDC-ACM much faster.

dmesg output after the udev rule change and service restart

```
[ 2573.482892] cdc_acm 1-2:1.0: ttyACM0: USB ACM device
[ 4085.164948] usb 1-2: USB disconnect, device number 8
[ 4341.098437] systemd-udevd[60195]: starting version 204
[ 4350.751727] usb 1-2: new full-speed USB device number 9 using xhci_hcd
[ 4350.996098] usb 1-2: New USB device found, idVendor=8087, idProduct=0aba
[ 4350.996101] usb 1-2: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[ 4350.996102] usb 1-2: Product: ATP-Dev1.0
[ 4350.996103] usb 1-2: Manufacturer: Intel
[ 4350.996104] usb 1-2: SerialNumber: 00.01
[ 4354.934080] usb 1-2: USB disconnect, device number 9
[ 4361.272132] usb 1-2: new full-speed USB device number 10 using xhci_hcd
[ 4363.393549] usb 1-2: New USB device found, idVendor=8087, idProduct=0ab6
[ 4363.393552] usb 1-2: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[ 4363.393553] usb 1-2: Product: CDC-ACM
[ 4363.393554] usb 1-2: Manufacturer: Intel
[ 4363.393555] usb 1-2: SerialNumber: 00.01
[ 4363.393806] usb 1-2: ep 0x81 - rounding interval to 64 microframes, ep desc says 80 microframes
[ 4363.395901] cdc_acm 1-2:1.0: ttyACM0: USB ACM device
```

However the error remains

```
/home/vraoresearch/CODK/CODK-M/arc/bin/resetPort.py /dev/ttyACM0
Resetting /dev/ttyACM0
Traceback (most recent call last):
  File "/home/vraoresearch/CODK/CODK-M/arc/bin/resetPort.py", line 12, in <module>
    mySerial = serial.Serial(serialPath, 1200)
  File "/usr/lib/python2.7/dist-packages/serial/serialutil.py", line 261, in __init__
    self.open()
  File "/usr/lib/python2.7/dist-packages/serial/serialposix.py", line 278, in open
    raise SerialException("could not open port %s: %s" % (self._port, msg))
serial.serialutil.SerialException: could not open port /dev/ttyACM0: [Errno 13] Permission denied: '/dev/ttyACM0'
make[1]: *** [upload] Error 1
make[1]: Leaving directory `/home/vraoresearch/CODK/CODK-M/arc/examples/ASCIITable'
make: *** [upload-arc-dfu] Error 2
```

**Comment by vraoresearch** [comment]
I tried to manually update the permissions

```
sudo chmod 777 /dev/ttyACM0
```

Then tried again

```
make upload-arc-dfu
```

This time the behavior is different and after a long wait it seems to succeed

```
dfu-util: A valid DFU suffix will be required in a future dfu-util release!!!
dfu-util: can't detach 
```

There was a couple of minute wait at this point before the script continued as below...

```
dfu-util 0.8

Copyright 2005-2009 Weston Schmidt, Harald Welte and OpenMoko Inc.
Copyright 2010-2014 Tormod Volden and Stefan Schmidt
This program is Free Software and has ABSOLUTELY NO WARRANTY
Please report bugs to dfu-util@lists.gnumonks.org

Opening DFU capable USB device...
ID 8087:0aba
Run-time device DFU version 0011
Claiming USB DFU Interface...
Setting Alternate Setting #7 ...
Determining device status: state = dfuIDLE, status = 0
dfuIDLE, continuing
DFU mode device DFU version 0011
Device returned transfer size 2048
Copying data from PC to DFU device
Download    [=========================] 100%        47720 bytes
Download done.
Sent a total of 47720 bytes
state(2) = dfuIDLE, status(0) = No error condition is present
Done!
Resetting USB to switch back to runtime mode
SUCCESS: Sketch will execute in about 5 seconds.
make[1]: Leaving directory `/home/vraoresearch/CODK/CODK-M/arc/examples/ASCIITable'
```

The VM GUI again shows 2 board icons and manually attempting to disconnect results in a driver error. If the board is unplugged the icons disappear normally and only one icon appears on reconnect.

Confirmed that app ASCIITable is working after the flash above.

**Comment by vraoresearch** [comment]
## Protocol Error

Another rarer error when running make upload

```
/home/vraoresearch/CODK/CODK-M/arc/arc32/bin/arc-elf32-objcopy -S -O ihex -R .note -R .comment -R COMMON -R .eh_frame  arc.elf arc.hex
Resetting port /dev/ttyACM0
/home/vraoresearch/CODK/CODK-M/arc/bin/resetPort.py /dev/ttyACM0
Resetting /dev/ttyACM0
Traceback (most recent call last):
  File "/home/vraoresearch/CODK/CODK-M/arc/bin/resetPort.py", line 14, in <module>
    mySerial.setDTR(level=False)
  File "/usr/lib/python2.7/dist-packages/serial/serialposix.py", line 535, in setDTR
    fcntl.ioctl(self.fd, TIOCMBIC, TIOCM_DTR_str)
IOError: [Errno 71] Protocol error
make: *** [upload] Error 1
```

**Comment by vraoresearch** [comment]
## Device not responding

Another error sometimes seen.

```
Resetting /dev/ttyACM0
Reset Complete!
sleep 1
Uploading compile to port /dev/ttyACM0
/home/vraoresearch/CODK/CODK-M/arc/bin/arduino101load /home/vraoresearch/CODK/CODK-M/arc/bin/x86/bin arc.bin /dev/ttyACM0 true
Starting download script...
Args to shell: [/home/vraoresearch/CODK/CODK-M/arc/bin/x86/bin arc.bin /dev/ttyACM0 true]
Serial Port: /dev/ttyACM0
BIN FILE arc.bin
Waiting for device...
Waiting for device...
Waiting for device...
Waiting for device...
Waiting for device...
Flashing is taking longer than expected
Try pressing MASTER_RESET button
Waiting for device...
Waiting for device...
Waiting for device...
Waiting for device...
Waiting for device...
ERROR: Device is not responding.
make: *** [upload] Error 1
```

**Comment by vraoresearch** [comment]
I tried two things that resulted in a lot of improvements:
First, in the 99-dfu.rules file, I added the appropriate GROUPS to tty and usb respectively.

```
ATTRS{idVendor}=="8087", ATTRS{idProduct}=="0ab[a6]", ENV{ID_MM_DEVICE_IGNORE}="1"
ATTRS{idVendor}=="8087", ATTRS{idProduct}=="0ab[a6]", ENV{MTP_NO_PROBE}="1"
SUBSYSTEM=="tty", ENV{ID_REVISION}=="8087", ENV{ID_MODEL_ID}=="0ab6", MODE="0666", GROUP="dialout"
SUBSYSTEM=="usb", ATTR{idVendor}=="8087", ATTR{idProduct}=="0aba", MODE="666", GROUP="plugdev"
```

Next I created a new rule file called 90-local.rule with the following contents

```
ACTION=="add", ATTRS{idProduct}=="0aba", ATTRS{idVendor}=="8087", DRIVERS=="usb", RUN+="chmod a+rw /dev/ttyACM0"
```

Incidentally I still continue to see mtp-probes despite the no probe you added.

```
Sep 22 21:33:37 ubuntu kernel: usb 2-2.2: new full-speed USB device number 58 using uhci_hcd
Sep 22 21:33:37 ubuntu kernel: usb 2-2.2: New USB device found, idVendor=8087, idProduct=0ab6
Sep 22 21:33:37 ubuntu kernel: usb 2-2.2: New USB device strings: Mfr=1, Product=2, SerialNumber=3
Sep 22 21:33:37 ubuntu kernel: usb 2-2.2: Product: ARDUINO 101
Sep 22 21:33:37 ubuntu kernel: usb 2-2.2: Manufacturer: Intel
Sep 22 21:33:37 ubuntu kernel: usb 2-2.2: SerialNumber: <BLANKED>
Sep 22 21:33:37 ubuntu kernel: cdc_acm 2-2.2:1.0: ttyACM0: USB ACM device
Sep 22 21:33:37 ubuntu mtp-probe[23350]: checking bus 2, device 58: "/sys/devices/pci0000:00/0000:00:11.0/0000:02:00.0/usb2/2-2/2-2.2"
Sep 22 21:33:37 ubuntu mtp-probe[23350]: bus: 2, device: 58 was not an MTP device
```

**Comment by vraoresearch** [comment]
I tried to add the ATTR lines into a new rule called 90-libmtp.rules

```
ATTRS{idVendor}=="8087", ATTRS{idProduct}=="0ab[a6]", ENV{ID_MM_DEVICE_IGNORE}="1"
ATTRS{idVendor}=="8087", ATTRS{idProduct}=="0ab[a6]", ENV{MTP_NO_PROBE}="1"
```

Now everything seems to behave itself...

The percentage of successful first time flashing is way way up now and if you allow for some settling time after plugging in the board on the USB, the double icons go away and things stabilize. When you get the occasional driver errors, simply unplug the board and wait for the error messages to go away.

**Comment by vraoresearch** [comment]
Finally I decided to bring out the heavy artillery
Added the following lines to /lib/udev/rules.d/69-libmtp.rules

```
Some sensitive devices we surely don't wanna probe
```

Under this comment heading that has a lot of devices, add

```
Sensitive Intel Curie Module
ATTR{idVendor}=="8087", ATTR{idProduct}=="0aba", GOTO="libmtp_rules_end"
```

After restarting udev and reloading rules ... Big difference now.  The settling time is much better.

**Comment by noelpaz** [comment]
If you are using a VMWare Player or WS, I would suggest powering the VM off and adding these lines in the .vmx file

usb.autoConnect.device0 = "vid:0x8087 pid:0x0ab6 autoclean:0"
usb.autoConnect.device1 = "vid:0x8087 pid:0x0aba autoclean:0"

This would solve USB connect issues

**Comment by vraoresearch** [comment]
## What Worked Best 
**What Changed:**
VMWare Workstation 12 Pro is now Version 12.5.2 build-4638234
Ubuntu version is **_16.04.1_** LTS Desktop
CODK-M Checked out Nov 30 2016

I did not need to do any of the extra configuration listed in the thread above.
Restored the board to Factory default using the installer from [here](https://downloadcenter.intel.com/downloads/eula/25470/Arduino-101-software-package?httpDown=https%3A%2F%2Fdownloadmirror.intel.com%2F25470%2Feng%2Farduino101-factory_recovery-flashpack.tar.bz2)

Now the board has no issues using DFU to upload. The upload is pretty quick.

**Comment by EricESM** [comment]
HI, I got a error like this:
chmod: cannot access ‘/dev/ttyACM0’: No such file or directory

vmware with ubuntu, the host is os
